# Generated by Django 4.1.7 on 2023-04-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='htmlquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qchar', models.CharField(default='', max_length=100)),
                ('wo1', models.CharField(default='', max_length=20)),
                ('wo2', models.CharField(default='', max_length=20)),
                ('wo3', models.CharField(default='', max_length=20)),
                ('ro', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
