# Generated by Django 4.1.7 on 2023-04-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_doubt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_user', models.CharField(default='', max_length=20)),
                ('feedback_user_email', models.EmailField(default=None, max_length=254)),
                ('feedback_content', models.CharField(default='', max_length=200)),
                ('feedback_rate', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_user', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default=None, max_length=30)),
                ('enrolled_course', models.CharField(default=None, max_length=30)),
                ('enrolled_id', models.CharField(default=None, max_length=30)),
                ('mobile_no', models.IntegerField(default=None, max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('order_id', models.CharField(default=None, max_length=30)),
                ('amount', models.IntegerField(default=None, max_length=10)),
            ],
        ),
    ]
