# Generated by Django 4.1.7 on 2023-04-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0005_feedback_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mobile_no',
            field=models.IntegerField(default=None),
        ),
    ]
